### ISSUE TITLE
An internal error occurred:  [Error: Queue restoration timeout]

### ISSUE THREAD

**Issue by jvgeee** [segmentio/analytics-react-native#1008]
On the latest (^2.19.5), I'm getting lots of warnings for `An internal error occurred:  [Error: Queue restoration timeout]`

<img width="504" alt="image" src="https://github.com/user-attachments/assets/60505681-75d4-465a-9943-80fbbd3f0f73">

It's clogging up my console and it's really annoying, dunno if it's causing any issues with transmitting events to Segment in the back-end as well. 

Potentially related to https://github.com/segmentio/analytics-react-native/issues/954, but not sure. I've been seeing these warnings since at least June.

**Comment by birat-pandey** [comment]
I'm having the same issue

**Comment by kagrawal98** [comment]
I'm also facing the same issue

**Comment by fcornejo-contalink** [comment]
Facing same issue here. Very annoying

**Comment by ThinhNT1** [comment]
same here, is there any solution?

**Comment by efstathiosntonas** [comment]
version 2.20.2 is out that includes a fix about it

**Comment by Edjees** [comment]
I still get one instance of  `WARN  An internal error occurred:  [Error: Queue restoration timeout]`

and a new message after it:

` WARN  Flush triggered but queue restoration and settings loading not complete. Flush will be retried. [Error: Promise timed out]`


But its not spamming anymore! I never saw any related messages before the recent updates though so I don't think its our code.

**Comment by LouisMuriuki** [comment]
![image](https://github.com/user-attachments/assets/e07631fa-1100-4f47-8af0-5affee09cd28)
Hello @alanjcharles i stll get the error on the latest version update.
i have tested this on android, kindly assist

**Comment by emmanuel-methodic** [comment]
I am still getting this error on the latest release

<img width="603" alt="Screenshot 2024-12-10 at 3 17 03 AM" src="https://github.com/user-attachments/assets/d9261e11-94c0-4ac0-a970-4294e79b1342">

**Comment by cunguyendev** [comment]
It was resolved on my side when I upgraded the packages below:
```json
"@segment/analytics-next": "^1.76.0",
"@segment/analytics-node": "^2.2.0",
"@segment/analytics-react-native": "^2.20.3",
"@segment/sovran-react-native": "^1.1.3",
```

**Comment by brycethornton** [comment]
I still get this error, but less so, after the upgrade to `2.20.3`. It appears the [fix](https://github.com/segmentio/analytics-react-native/pull/1013) was to limit the error to once per session (in-memory tracking). It's definitely super noisy for us as it gets sent to Sentry as an error. Is there a good way to completely suppress this? Or, should I be worrying about it because it truly means something broke?  cc/ @alanjcharles

**Comment by neyosoft** [comment]
Please any solution to this issue?

**Comment by brycethornton** [comment]
@neyosoft I ended up just patching the package in my project with the [error code](https://github.com/segmentio/analytics-react-native/blob/6153e20eb75d120193d1161fdee5ec85a3c74341/packages/core/src/plugins/QueueFlushingPlugin.ts#L88-L94) commented out.

**Comment by neyosoft** [comment]
Thank you @brycethornton 
I guess i'd have to do the same for now because all the the logs is being sent to sentry as an error.
I believe a fix on this package will be extremely helpful.

**Comment by dwxw** [comment]
I've had this warning for a while, but since upgrading to RN 0.78 a further error is triggered because of an [issue](https://github.com/facebook/react-native/issues/43636) in Hermes.  Should I be concerned that the event queue always times out when our app starts?  Would increasing the timeout help?

**Comment by jakekreider** [comment]
I've also noticed this with upgrade to Expo 53/RN 0.79. We've also noticed a drop in events for confirmed users, but I haven't correlated to this error.
