### ISSUE TITLE
RNAnalytics try to override RNAnalyticsModule

### ISSUE THREAD

**Issue by YevheniiShabelnykkk** [segmentio/analytics-react-native#139]
Hello! Can anybody help with this error for Android? For IOS everything is ok.

My MainApplication.java file looks like this:
```package com.plutotravel;

import android.app.Application;


import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.segment.analytics.reactnative.core.RNAnalyticsPackage;

import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;

import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import io.intercom.android.sdk.Intercom;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new ReactNativeFirebaseMessagingPackage());
      
      packages.add(new RNFirebaseNotificationsPackage());
      packages.add(new RNFirebaseAnalyticsPackage());
      packages.add(new RNFirebaseMessagingPackage());
      packages.add(new RNAnalyticsPackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    Intercom.initialize(this, "android_sdk-4345c0d66d1bd0d2f7a25d8027548d5c082388ea", "ezgo40ii");

    SoLoader.init(this, /* native exopackage */ false);
    
  }
}
```

Yes, if I remove this line `packages.add(new RNAnalyticsPackage());` error disappears, but analytics will not work.

Could you help please.

<img width="314" alt="Screen Shot 2020-02-28 at 2 47 11 PM" src="https://user-images.githubusercontent.com/53472115/75552421-f0a46800-5a3e-11ea-9f11-d2579f69441b.png">

**Comment by bsneed** [comment]
I believe this is resolved in the latest betas.  If not, please reopen this issue.

**Comment by 82rules** [comment]
Experiencing this same issue, upgrading to latest beta v5 did not resolve. Any insights?
