### ISSUE TITLE
Crash caused by setup code

### ISSUE THREAD

**Issue by nishsinghal** [segmentio/analytics-react-native#145]
Hi, we're seeing lots of crashes in our iOS production app. The errors in Sentry seem to suggest that the issue is somewhere around the setup code but I'm struggling to see where and struggling to reproduce it.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/8045545/76849818-0f2ba100-683e-11ea-838c-c1cf21c2284a.png">

This is our JS code where `REACT_APP_SEGMENT` is the segment key:
```
analytics.setup(REACT_APP_SEGMENT, {
    trackAppLifecycleEvents: true,
    recordScreenViews: false,
});
```

We're using cocoapods but it's currently set up to pull the latest master version of the ios library

segmentio/analytics-react-native: v1.1.0
segmentio/analytics-ios: `24abc1fcc93873be6ddeef08f61658421ccca671` <-- this is the commit that is in the `Podfile.lock`

Any help would be much appreciated!

**Comment by nishsinghal** [comment]
There's also another related crash:
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/8045545/76853831-f0310d00-6845-11ea-8d2a-0325c351bf37.png">

**Comment by bsneed** [comment]
@nishsinghal this issue is fixed in the latest beta for analytics-ios.  Please update to that and you should be good.

**Comment by nishsinghal** [comment]
@bsneed We upgraded to `3.8.0-beta.1` for `analytics-ios` and were still seeing crashes with so have had to resort to removing Segment for the timebeing for our iOS builds. We'd really like to be able to turn it back on though.
```
NSInvalidArgumentException
-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x282493da0
```

**Comment by bsneed** [comment]
@nishsinghal I'll need more information to be able to help you.  You may have to debug it a little, ie: what are reproduction steps?  What line of code is getting hit in your debugger?  What are the variable values in that particular scope?  I can't really help without that as we're not seeing this issue across the board.

**Comment by karl** [comment]
For anyone else who comes across this problem here is some more info we discovered:

- The crash DOES NOT occur on stable releases (e.g. `3.7.1`).
- The crash only occurs on the `3.8.0` beta releases.
- It looks like a fix has been merged to `master` for this bug, but it was NOT in the `3.8.0-beta.1` release.

Fingers crossed no else ends up spending as long debugging this as we did 😂

**Comment by bsneed** [comment]
@karl so sorry to hear that.  :(

the good news is, I'll be pushing out a new beta later today.
