### ISSUE TITLE
[iOS] Cannot  build anymore

### ISSUE THREAD

**Issue by rborn** [segmentio/analytics-react-native#195]
Hi,

Since a few days ago I started to get this error when trying to build for iOS

`[project_path]/Segment-Amplitude/Pod/Classes/SEGAmplitudeIntegrationFactory.h:2:9: 'Analytics/Analytics.h' file not found`

I didn't change anything in my project and I have tried everything I could think of, but I don't seem to find a fix.
Any ideas?

Thanks

**Comment by bsneed** [comment]
Hi @rborn there's been some changes in that amplitude integration to allow it to work with analytics-ios 4.0.4.  You may need to do a pod install or pod update to get the latest for each.  Let us know if that doesn't get things working for you and we'll dive in.

**Comment by rborn** [comment]
Hi @bsneed , thanks for the reply.

The only way I managed to make it work (just 1h ago) keeping 1.1.1-beta.2 but forcing an updated pod.

If I try to update to 1.2.1, the pod becomes a dependency forced to 3.9.0 that fails to compile.

**Comment by yuriceschin** [comment]
Hi @bsneed 
I have the exact same problem. I tried pod install/update, restart everything from scratch but I still get: "/ios/Pods/Segment-Amplitude/Pod/Classes/SEGAmplitudeIntegration.h:2:9: 'Analytics/Analytics.h' file not found"

I also tried to keep the old version but something isn't working. @rborn Can you explain how you have done it in detail? I'm quite a newbie.

Thanks!

**Comment by vescogma** [comment]
Same issue here

**Comment by rborn** [comment]
@yuriceschin I used in package.json this specific version
~~~
 "@segment/analytics-react-native": "1.1.1-beta.2",
 "@segment/analytics-react-native-amplitude": "1.1.1-beta.2",
~~~ 

And in Podfile I've put 
~~~
  pod "Analytics"
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
  pod 'RNAnalyticsIntegration-Amplitude', :path => '../node_modules/@segment/analytics-react-native-amplitude'
~~~

Clean your pod cache , ios/Pods folder, remove Podfile.lock and run pods install again. Keep an eye to get the Analytics 4.0.4 version and it should work

It looks like there is a fix for it though: https://github.com/segmentio/analytics-react-native/commit/cba5666080985ef79c317997f72a5ce13d3f9fe7#diff-7bb11dff82641e759fe6df1c37a1fab6L23  but probably not yet published

What you could try is after you install the integration packages (amplitude) to go to it's podspec file and remove 3.9.0 and run pod install (I didn't have the time to try this) but this will reset each time you run npm install

**Comment by barakd** [comment]
> @yuriceschin I used in package.json this specific version
> 
> ```
>  "@segment/analytics-react-native": "1.1.1-beta.2",
>  "@segment/analytics-react-native-amplitude": "1.1.1-beta.2",
> ```
> 
> And in Podfile I've put
> 
> ```
>   pod "Analytics"
>   pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
>   pod 'RNAnalyticsIntegration-Amplitude', :path => '../node_modules/@segment/analytics-react-native-amplitude'
> ```
> 
> Clean your pod cache , ios/Pods folder, remove Podfile.lock and run pods install again. Keep an eye to get the Analytics 4.0.4 version and it should work
> 
> It looks like there is a fix for it though: [cba5666#diff-7bb11dff82641e759fe6df1c37a1fab6L23](https://github.com/segmentio/analytics-react-native/commit/cba5666080985ef79c317997f72a5ce13d3f9fe7#diff-7bb11dff82641e759fe6df1c37a1fab6L23) but probably not yet published
> 
> What you could try is after you install the integration packages (amplitude) to go to it's podspec file and remove 3.9.0 and run pod install (I didn't have the time to try this) but this will reset each time you run npm install

Hi your suggestion indeed works, I kept using the latest version (1.2.1)
and added the following command to my project postinstall script
`sed -i ''  "s/'Analytics', '3.9.0'/'Analytics'/g" node_modules/@segment/analytics-react-native/RNAnalytics.podspec`
tested on MacOS

**Comment by rborn** [comment]
@barakd usually for this  `patch-package` is used (more robust and safer than a simple script) 
There are few articles around explaining how to do it, but great job nevertheless 😻

**Comment by bsneed** [comment]
Quick update on this issue:  I've made all the necessary fixes, however I had to open a PR with CleverTap to put some changes in their self-maintained integration.  PR is here: https://github.com/CleverTap/clevertap-segment-ios/pull/11

Once that gets merged in, I'll post a new release that fixes this.

**Comment by paulxuca** [comment]
Any update on this issue?

**Comment by rborn** [comment]
@bsneed looks like your PR is merged  in CleverTap 😻

**Comment by bsneed** [comment]
@rborn Yup!  We've got one more change we're waiting on internally around IDFA and iOS 14.  I'm trying to get to it either today or tomorrow and we'll close this out.

**Comment by bsneed** [comment]
Haha thanks for always cheering us on @rborn ! 🙏

**Comment by rborn** [comment]
@bsneed sorry to be a pita, any news? 😅

**Comment by bsneed** [comment]
@rborn No worries!  I just pushed out a release.  It makes some changes to how IDFA is handled in addition to fixing this issue.

**Comment by rborn** [comment]
@bsneed I think there is still an issue

```
[!] CocoaPods could not find compatible versions for pod "Analytics":
  In Podfile:
    RNAnalytics (from `../node_modules/@segment/analytics-react-native`) was resolved to 1.3.0, which depends on
      Analytics (~> 4.0.5)

    RNAnalyticsIntegration-Amplitude (from `../node_modules/@segment/analytics-react-native-amplitude`) was resolved to 1.3.0, which depends on
      Analytics

Specs satisfying the `Analytics, Analytics (~> 4.0.5)` dependency were found, but they required a higher minimum deployment target.
```


RNAnalytics seems to still have a hardcoded dependency

```
  s.dependency          'Analytics', '~> 4.0.5'
```

I removed the version and pods installs well and seems to send events to segment fine. 

```
  s.dependency          'Analytics'
```

How can I help make a new release with this fix? 😻

**Comment by bsneed** [comment]
@rborn Yes, that change is required. Our iOS lib minimum is now 11.0. That's my bad on not bumping the version #'s appropriately given it was indeed a breaking change. My apologies for that. If you need 10.x support, we recommend you move back to a previous version.  But 4.0.5 is required.

**Comment by rborn** [comment]
@bsneed ok understood, no need to apologise 🤗 
I'm in process of upgrading target ios to 11.0 so will check the fix,  I'll comeback if anything :)
Thanks

**Comment by alacret** [comment]
Hello, this is happening for the version >= 2.0.0 

I perform some tests of 2.1.7 and 2.2.2 having the same problem

package.json

```
...
    "@segment/analytics-react-native": "2.0.0",
    "@segment/analytics-react-native-clevertap": "1.5.1",
    "@segment/analytics-react-native-firebase": "1.5.3",
    "@segment/sovran-react-native": "^0.2.8",
    ...
```


```sh
[!] Unable to find a specification for `RNAnalytics` depended upon by `RNAnalyticsIntegration-CleverTap`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Couldn't install: RNAnalyticsIntegration-CleverTap » RNAnalytics. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: Unable to find a specification for `RNAnalytics` depended upon by `RNAnalyticsIntegration-CleverTap`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

any recommendation?
