### ISSUE TITLE
Module FirebaseCore not found

### ISSUE THREAD

**Issue by raybotha** [segmentio/analytics-react-native#314]
The latest changes in the Segment Firebase iOS integration breaks React Native (https://github.com/segment-integrations/analytics-ios-integration-firebase/commits/master).

Xcode build error `Module FirebaseCore not found` in SEGFirebaseIntegration.m line 3.

I had to reverse the changes made to SEGFirebaseIntegration.m and the other import changes that error to get it working again, like this:

```
//@import FirebaseCore;
//@import FirebaseAnalytics;

#import <Firebase/Firebase.h>
```

**Comment by raybotha** [comment]
FYI many react native libraries don't work with `use_frameworks!` in the Podfile, so changing that in my project is not really an option.

**Comment by bsneed** [comment]
Unless you need those changes, you might want to pin to a previous version.  We're having an extremely hard time supporting all the build combinations possible with these things between package managers, customers, vendors and ourselves unfortunately.  We're looking at tackling the overall issue in the very near future but it's a few months out still.

**Comment by raybotha** [comment]
The issue affects the default installation of this package so I'd suggest at least testing a fix to pin the version and modifying the readme before closing the issue, else users are left on their own to figure out why the Segment documentation is incorrect.

**Comment by bsneed** [comment]
Thanks @raybotha; that's a great callout that I didn't consider.  @alanjcharles can you take care of making this change and issuing a new release?

**Comment by alexpchin** [comment]
Looking forward to this fix. In the meantime, do you have a patch file?

**Comment by alanjcharles** [comment]
I've tested this fix locally and it builds as expected. I have to adjust our ci tests a bit to account for it but will update everyone here when we push the fix.

**Comment by RohovDmytro** [comment]
> Unless you need those changes, you might want to pin to a previous version. We're having an extremely hard time supporting all the build combinations possible with these things between package managers, customers, vendors and ourselves unfortunately. We're looking at tackling the overall issue in the very near future but it's a few months out still.

Hi! As a developer, I can understand your pain.

But from a perspective of a service... The main promise of Segment is to take care about this exactly pain.

Again. I'm totally with you as a developer. But it's frustrating when I'm in a position of a client.

Anyway, good luck with solving the issue! I hope you'd get a solid foundation to nail the connections.

**Comment by alanjcharles** [comment]
@RohovDmytro apologies for the inconvenience. This is definitely something we recognize and are working to correct for more long-term stability (stay tuned!). We will let you know when we have a fix pushed. Thanks for your patience

**Comment by alanjcharles** [comment]
Please upgrade to `@segment/analytics-react-native-firebase 1.4.5` to resolve this issue.

**Comment by alexpchin** [comment]
I've just upgraded to 1.4.5 but am still seeing the error `Module 'FirebaseCore' not found`.
